/// Flutter icons GBloxCustomSVGs
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GBloxCustomSVGs
///      fonts:
///       - asset: fonts/GBloxCustomSVGs.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GBloxCustomSVGs {
  GBloxCustomSVGs._();

  static const _kFontFam = 'GBloxCustomSVGs';
  static const String? _kFontPkg = null;

  static const IconData horn = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gBloxLogo = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headlights = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forwardMovement = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData randomMovement = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotateMovement = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_23 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speedometerBar = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData followLight = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avoidLight = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avoidobstacle = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData followobstacle = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolboxmath = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolboxled = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolboxloops = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolboxtext = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolboxsound = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolboxactuators = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolboxcom_1 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolboxlogic_1 = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolboxsensors = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
